name: Deploy to GitHub Pages

on:
  release:
    types: [created]
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      
      - name: Setup gh-pages
        run: |
          # Создаем или переключаемся на чистую gh-pages ветку
          git checkout --orphan gh-pages-new
          git reset --hard
          
      - name: Deploy
        run: |
          # Определяем тип деплоя
          if [ "${{ github.event_name }}" == "release" ]; then
            TAG="${{ github.event.release.tag_name }}"
            IS_RELEASE=true
          else
            TAG="latest"
            IS_RELEASE=false
          fi
          
          REPO_NAME="${{ github.repository }}"
          REPO_NAME=${REPO_NAME#*/}  # Убираем username/
          
          echo "🚀 Deploying: $TAG"
          echo "📦 Is release: $IS_RELEASE"
          
          # Копируем файлы из main ветки
          git checkout main -- .
          
          if [ "$IS_RELEASE" == "true" ]; then
            # Для релиза создаем версионную директорию
            mkdir -p "versions/$TAG"
            cp -r * "versions/$TAG/" 2>/dev/null || true
            
            # Создаем индекс версий
            cat > "versions/index.html" << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <meta charset="UTF-8">
              <title>Версии сайта</title>
              <style>
                  body { font-family: Arial; max-width: 600px; margin: 50px auto; padding: 20px; }
                  h1 { color: #333; }
                  a { color: #007acc; text-decoration: none; }
                  a:hover { text-decoration: underline; }
                  .version { margin: 10px 0; padding: 10px; background: #f5f5f5; }
              </style>
          </head>
          <body>
              <h1>Доступные версии</h1>
              <div id="versions"></div>
              <script>
                  // Автоматически находим версии
                  fetch('.')
                      .then(r => r.text())
                      .then(html => {
                          const parser = new DOMParser();
                          const doc = parser.parseFromString(html, 'text/html');
                          const links = Array.from(doc.querySelectorAll('a'))
                              .map(a => a.href)
                              .filter(href => href && !href.includes('index.html'))
                              .map(href => href.replace(/\/$/, ''));
                          
                          const container = document.getElementById('versions');
                          if (links.length === 0) {
                              container.innerHTML = '<p>Версии пока не созданы</p>';
                          } else {
                              links.forEach(version => {
                                  const div = document.createElement('div');
                                  div.className = 'version';
                                  div.innerHTML = `<a href="${version}/">🚀 ${version}</a>`;
                                  container.appendChild(div);
                              });
                          }
                      });
              </script>
          </body>
          </html>
          EOF
                    fi
                    
                    # Удаляем CI файлы из деплоя
                    rm -rf .github
                    
                    # Коммитим и принудительно пушим
                    git add .
                    git commit -m "Deploy $TAG"
                    git push origin gh-pages-new:gh-pages --force
                    echo "🎉 Deployed successfully!"